//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFZooManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLecture
    {
        public int Id { get; set; }
        public int StudentId { get; set; }
        public int LectureId { get; set; }
    
        public virtual Lecture Lecture { get; set; }
        public virtual Lecture Lecture1 { get; set; }
        public virtual Lecture Lecture2 { get; set; }
        public virtual Student Student { get; set; }
        public virtual Student Student1 { get; set; }
    }
}
