//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFZooManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZooAnimal
    {
        public int Id { get; set; }
        public int ZooId { get; set; }
        public int AnimalId { get; set; }
    
        public virtual Animal Animal { get; set; }
        public virtual Zoo Zoo { get; set; }
    }
}
