//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFZooManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZooDbEntities : DbContext
    {
        public ZooDbEntities()
            : base("name=ZooDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Animal> Animal { get; set; }
        public virtual DbSet<Lecture> Lecture { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<StudentLecture> StudentLecture { get; set; }
        public virtual DbSet<University> University { get; set; }
        public virtual DbSet<Zoo> Zoo { get; set; }
        public virtual DbSet<ZooAnimal> ZooAnimal { get; set; }
    }
}
